# Generated by Django 3.0.8 on 2020-08-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('type', models.TextField(choices=[('D', 'DEBIT'), ('C', 'CREDIT')], max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=50)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
