# Generated by Django 3.0.8 on 2020-08-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_bank_csv', '0003_auto_20200811_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sbject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
