# Generated by Django 3.0.8 on 2020-08-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_bank_csv', '0005_transaction_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='check_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sbject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
