# Generated by Django 3.0.8 on 2020-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_bank_csv', '0006_auto_20200811_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='check_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
