# Generated by Django 3.0.8 on 2020-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_bank_csv', '0011_auto_20200811_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Travels', 'TRAVELS'), ('Food', 'FOOD'), ('Donation', 'DONATION'), ('Grocery', 'GROCERY'), ('MonthlyRent', 'MONTHLY RENT'), ('Shopping', 'SHOPPING'), ('UtilityBills', 'UTILITY BITTS'), ('Call&Internet', 'CALL AND INTERNET'), ('Entertanment', 'ENTERTANMENT'), ('Clothing', 'CLOTHING'), ('Loan', 'LOAN OR HELP'), ('Investment', 'INVESTMENT'), ('Education', 'EDUCATION'), ('EarnedIncome', 'EARNED INCOME'), ('BusinessIncome', 'BUSINESS INCOME'), ('InvestmentIncome', 'INVESTMENT INCOME'), ('Salary', 'SALARY'), ('Wage', 'WAGE'), ('Others', 'OTHERS'), ('None', 'NONE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
