# Generated by Django 3.0.8 on 2020-08-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_bank_csv', '0013_auto_20200811_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Travels', 'TRAVELS'), ('Food', 'FOOD'), ('Donation', 'DONATION'), ('Grocery', 'GROCERY'), ('MonthlyRent', 'MONTHLY RENT'), ('Shopping', 'SHOPPING'), ('UtilityBills', 'UTILITY BITTS'), ('Call&Internet', 'CALL AND INTERNET'), ('Entertanment', 'ENTERTANMENT'), ('Clothing', 'CLOTHING'), ('Help', 'HELP'), ('Investment', 'INVESTMENT'), ('Education', 'EDUCATION'), ('Loan', 'LOAN'), ('EarnedIncome', 'EARNED INCOME'), ('BusinessIncome', 'BUSINESS INCOME'), ('InvestmentIncome', 'INVESTMENT INCOME'), ('SoldIteams', 'SOLD ITEMS'), ('Coupons', 'COUPONS'), ('Salary', 'SALARY'), ('Wage', 'WAGE'), ('Others', 'OTHERS'), ('None', 'NONE')], max_length=30, null=True),
        ),
    ]
