# Generated by Django 3.0.8 on 2020-08-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_bank_csv', '0019_auto_20200814_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('BusinessIncome', 'BUSINESS INCOME'), ('Call&Internet', 'CALL AND INTERNET'), ('CashWithdraw', 'CASH WITHDRAW'), ('Clothing', 'CLOTHING'), ('Coupons', 'COUPONS'), ('Donation', 'DONATION'), ('EarnedIncome', 'EARNED INCOME'), ('Education', 'EDUCATION'), ('Entertanment', 'ENTERTANMENT'), ('Food', 'FOOD'), ('Grocery', 'GROCERY'), ('Health&Medicine', 'HEALTH AND MEDICINE'), ('Help', 'HELP'), ('Investment', 'INVESTMENT'), ('InvestmentIncome', 'INVESTMENT INCOME'), ('Loan', 'LOAN'), ('MonthlyRent', 'MONTHLY RENT'), ('None', 'NONE'), ('Others', 'OTHERS'), ('RefundORCancle', 'REFUND OR CANCLE'), ('Salary', 'SALARY'), ('Shopping', 'SHOPPING'), ('SoldIteams', 'SOLD ITEMS'), ('Transport', 'TRANSPORT'), ('UtilityBills', 'UTILITY BITTS'), ('Wage', 'WAGE')], max_length=30, null=True),
        ),
    ]
